title: Welcome to Vimal's Blog page ...
author: Authored by Vimal Jani
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first blog page. In this blog page I would write about
  how awesome and powerful is Git and how easy it is to use Jekyll with
  Git to author and publish web page very quickly  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
